"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebsiteOptions = exports.Events = void 0;
__exportStar(require("./enums/file-submission-type.enum"), exports);
__exportStar(require("./enums/submission-rating.enum"), exports);
__exportStar(require("./enums/submission-type.enum"), exports);
const Events = __importStar(require("./events/events"));
exports.Events = Events;
__exportStar(require("./interfaces/account/user-account.dto.interface"), exports);
__exportStar(require("./interfaces/account/user-account.interface"), exports);
__exportStar(require("./interfaces/custom-shortcut/custom-shortcut.interface"), exports);
__exportStar(require("./interfaces/database/entity.interface"), exports);
__exportStar(require("./interfaces/description-template/description-template.interface"), exports);
__exportStar(require("./interfaces/file-manager/uploaded-file.interface"), exports);
__exportStar(require("./interfaces/notification/postybirb-notification.interface"), exports);
__exportStar(require("./interfaces/notification/ui-notification.interface"), exports);
__exportStar(require("./interfaces/settings/settings.interface"), exports);
__exportStar(require("./interfaces/submission/default-options.interface"), exports);
__exportStar(require("./interfaces/submission/description-data.interface"), exports);
__exportStar(require("./interfaces/submission/file-record.interface"), exports);
__exportStar(require("./interfaces/submission/file-submission.interface"), exports);
__exportStar(require("./interfaces/submission/post-response.interface"), exports);
__exportStar(require("./interfaces/submission/post-status.interface"), exports);
__exportStar(require("./interfaces/submission/problems.interface"), exports);
__exportStar(require("./interfaces/submission/submission-create.interface"), exports);
__exportStar(require("./interfaces/submission/submission-import.interface"), exports);
__exportStar(require("./interfaces/submission/submission-log.interface"), exports);
__exportStar(require("./interfaces/submission/submission-overwrite.interface"), exports);
__exportStar(require("./interfaces/submission/submission-package.interface"), exports);
__exportStar(require("./interfaces/submission/submission-part.interface"), exports);
__exportStar(require("./interfaces/submission/submission-schedule.interface"), exports);
__exportStar(require("./interfaces/submission/submission-template-update.interface"), exports);
__exportStar(require("./interfaces/submission/submission-template.interface"), exports);
__exportStar(require("./interfaces/submission/submission-update.interface"), exports);
__exportStar(require("./interfaces/submission/submission.interface"), exports);
__exportStar(require("./interfaces/submission/tag-data.interface"), exports);
__exportStar(require("./interfaces/tag-converter/tag-converter.interface"), exports);
__exportStar(require("./interfaces/tag-group/tag-group.interface"), exports);
__exportStar(require("./interfaces/websites/artconomy/artconomy.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/aryion/aryion.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/custom/custom.account.interface"), exports);
__exportStar(require("./interfaces/websites/derpibooru/derpibooru.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/furbooru/furbooru.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/deviant-art/deviant-art.account.interface"), exports);
__exportStar(require("./interfaces/websites/deviant-art/deviant-art.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/discord/discord.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/discord/discord.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/e621/e621.account.interface"), exports);
__exportStar(require("./interfaces/websites/e621/e621.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/folder.interface"), exports);
__exportStar(require("./interfaces/websites/fur-affinity/fur-affinity.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/fur-affinity/fur-affinity.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/furry-network/furry-network.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/furry-network/furry-network.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/furtastic/furtastic.account.interface"), exports);
__exportStar(require("./interfaces/websites/furtastic/furtastic.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/hentai-foundry/hentai-foundry.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/inkbunny/inkbunny.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/ko-fi/ko-fi.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/manebooru/manebooru.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/megalodon/megalodon.account.interface"), exports);
__exportStar(require("./interfaces/websites/mastodon/mastodon.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/mastodon/mastodon.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/misskey/misskey.account.interface"), exports);
__exportStar(require("./interfaces/websites/misskey/misskey.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/misskey/misskey.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/pleroma/pleroma.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/pleroma/pleroma.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/newgrounds/newgrounds.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/patreon/patreon.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/patreon/patreon.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/picarto/picarto.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/piczel/piczel.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/pillowfort/pillowfort.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/pillowfort/pillowfort.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/pixiv/pixiv.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/so-furry/so-furry.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/so-furry/so-furry.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/subscribe-star/subscribe-star.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/subscribe-star/subscribe-star.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/tumblr/tumblr.account.interface"), exports);
__exportStar(require("./interfaces/websites/tumblr/tumblr.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/tumblr/tumblr.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/username-shortcut.interface"), exports);
__exportStar(require("./interfaces/websites/weasyl/weasyl.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/itaku/itaku.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/itaku/itaku.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/telegram/telegram.account.interface"), exports);
__exportStar(require("./interfaces/websites/telegram/telegram.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/telegram/telegram.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/pixelfed/pixelfed.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/bluesky/bluesky.account.interface"), exports);
__exportStar(require("./interfaces/websites/bluesky/bluesky.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/bluesky/bluesky.notification.options.interface"), exports);
__exportStar(require("./interfaces/websites/twitter/twitter.file.options.interface"), exports);
__exportStar(require("./interfaces/websites/twitter/twitter.account.interface"), exports);
__exportStar(require("./models/default-options.entity"), exports);
__exportStar(require("./models/default-file-options.entity"), exports);
const WebsiteOptions = __importStar(require("./websites/websites"));
exports.WebsiteOptions = WebsiteOptions;
__exportStar(require("./websites/megalodon/megalodon.instancesettings"), exports);
